version: '3.8'

name: prisma-prisma

# For connection urls to the following instances, see
# https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    # Uncomment the following line to enable query logging
    # Then restart the container.
    # command: ['postgres', '-c', 'log_statement=all']
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5432:5432'